"""
backend/models/adventure_log.py
Pydantic models for Adventure Log API.

These models define the schema for room visit summaries and adventure context.
Used for narrative continuity when transitioning between rooms.
"""
from typing import Optional, List
from pydantic import BaseModel, Field, field_validator


class NPCInteractionSummary(BaseModel):
    """Summary of a single NPC interaction during a room visit."""
    npc_uuid: str
    npc_name: str
    relationship_change: str = "neutral"  # improved, worsened, neutral
    notable_interaction: str = ""  # Max 60 characters

    @field_validator('relationship_change')
    @classmethod
    def validate_relationship_change(cls, v: str) -> str:
        allowed = {'improved', 'worsened', 'neutral'}
        if v not in allowed:
            return 'neutral'
        return v

    @field_validator('notable_interaction')
    @classmethod
    def truncate_notable_interaction(cls, v: str) -> str:
        return v[:60] if v else ""


class ItemChange(BaseModel):
    """Record of an item change during a room visit."""
    item: str
    action: str  # acquired, used, lost, traded

    @field_validator('action')
    @classmethod
    def validate_action(cls, v: str) -> str:
        allowed = {'acquired', 'used', 'lost', 'traded'}
        if v not in allowed:
            return 'acquired'
        return v


class RoomSummary(BaseModel):
    """
    Summary of a single room visit.
    Generated by LLM summarization or keyword extraction fallback.
    """
    room_uuid: str
    room_name: str
    visited_at: int  # Epoch milliseconds
    departed_at: int  # Epoch milliseconds
    message_count: int = 0
    key_events: List[str] = Field(default_factory=list)  # Max 3
    npcs_interacted: List[NPCInteractionSummary] = Field(default_factory=list)
    items_changed: List[ItemChange] = Field(default_factory=list)
    unresolved_threads: List[str] = Field(default_factory=list)  # Max 2
    mood_on_departure: str = "neutral"  # hopeful, wounded, triumphant, fearful, curious, neutral

    @field_validator('key_events')
    @classmethod
    def limit_key_events(cls, v: List[str]) -> List[str]:
        return v[:3] if v else []

    @field_validator('unresolved_threads')
    @classmethod
    def limit_unresolved_threads(cls, v: List[str]) -> List[str]:
        return v[:2] if v else []


class AdventureLogEntry(BaseModel):
    """
    Single adventure log entry as stored in the database.
    Represents one visit to a room.
    """
    id: Optional[int] = None
    world_uuid: str
    user_uuid: str
    room_uuid: str
    room_name: str
    visited_at: int
    departed_at: Optional[int] = None
    message_count: int = 0
    summary: Optional[RoomSummary] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class AdventureLogEntryCreate(BaseModel):
    """Request model for creating a new adventure log entry (on room enter)."""
    world_uuid: str
    user_uuid: str
    room_uuid: str
    room_name: str
    visited_at: int


class AdventureLogEntryComplete(BaseModel):
    """Request model for completing an adventure log entry (on room exit)."""
    departed_at: int
    message_count: int
    summary: RoomSummary


class AdventureContext(BaseModel):
    """
    Cumulative adventure context for a world playthrough.
    Used for injecting journey history into LLM context.
    """
    world_uuid: str
    user_uuid: str
    entries: List[RoomSummary] = Field(default_factory=list)
    current_objectives: List[str] = Field(default_factory=list)
    total_rooms_visited: int = 0
    total_message_count: int = 0


# Request/Response models for endpoints

class SummarizeMessageInput(BaseModel):
    """Single message for summarization."""
    role: str  # user, assistant, system
    content: str


class SummarizeNPCInput(BaseModel):
    """NPC data for matching in summarization."""
    id: str
    name: str


class SummarizeRoomRequest(BaseModel):
    """Request payload for POST /api/context/summarize-room."""
    world_uuid: str
    user_uuid: str
    room_uuid: str
    room_name: str
    visited_at: int
    messages: List[SummarizeMessageInput] = Field(default_factory=list)
    npcs: List[SummarizeNPCInput] = Field(default_factory=list)


class SummarizeRoomResponse(BaseModel):
    """Response from POST /api/context/summarize-room."""
    summary: RoomSummary
    method: str  # "llm" or "fallback"


def create_empty_room_summary(
    room_uuid: str,
    room_name: str,
    visited_at: int
) -> RoomSummary:
    """Create an empty/default RoomSummary."""
    import time
    return RoomSummary(
        room_uuid=room_uuid,
        room_name=room_name,
        visited_at=visited_at,
        departed_at=int(time.time() * 1000),
        message_count=0,
        key_events=[],
        npcs_interacted=[],
        items_changed=[],
        unresolved_threads=[],
        mood_on_departure="neutral"
    )


def create_empty_adventure_context(
    world_uuid: str,
    user_uuid: str
) -> AdventureContext:
    """Create an empty AdventureContext for a new playthrough."""
    return AdventureContext(
        world_uuid=world_uuid,
        user_uuid=user_uuid,
        entries=[],
        current_objectives=[],
        total_rooms_visited=0,
        total_message_count=0
    )
